//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etudiant
    {
        public int Id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string datenaissance { get; set; }
        public string classe { get; set; }
    }
}
